version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/dotnet/
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: /src/java/
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
